{% set name = "e340py" %}
{% set data = load_setup_py_data() %}

#https://groups.google.com/a/continuum.io/forum/#!topic/conda/zOLMF4CfnAU

package:
  name: '{{ name|lower }}'
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  noarch: python

  entry_points:
    
    - dump_comments = e340py.dump_comments:main
    - find_links = e340py.find_links:main
    - add_points = e340py.add_points:main
    
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
    - setuptools_scm
  run:
    - python
    - numpy
    - pandas

test:
  imports:
    - e340py
  requires:
    - numpy
    - pandas
  commands:
    - dump_comments --help


about:
  home: https://clouds.eos.ubc.ca/~phil/courses
  license: MIT
  summary: 'e340 courseware'

extra:
  recipe-maintainers:
    - phaustin
    
